### ISSUE TITLE
[FEA] Update Python bindings for ingress/egress creation to take a pybind11 object typeid

### ISSUE THREAD

**Issue by drobison00** [nv-morpheus/SRF#135]
**Is your feature request related to a problem? Please describe.**
This is an optimization; we want to be able to create ingress/egress nodes from Python that can be directly connected to their c++ equivalent data type without first converting to a PyHolder / py::object. 

**Describe the solution you'd like**
Update ingress/egress bindings to take either a list (current implementation) with names that result in XXPort\<PyHolder\>, or a list of tuples of (name, typeid) format, so we can dynamically connected edges at run time without the c++->python->c++ overhead

**Comment by mdemoret-nv** [comment]
Closed in PR #153
