### ISSUE TITLE
[BUG] cpp test failure in TestNetwork.ResourceManager

### ISSUE THREAD

**Issue by pdmack** [nv-morpheus/SRF#138]
**Describe the bug**

branch-22.08

```
[ RUN      ] TestNetwork.ResourceManager
[1657658579.822927] [r740-64-137:2207514:0]         cuda_md.c:162  UCX  ERROR cuMemGetAddressRange(0x7fbe1c000000) error: named symbol not found
[1657658579.823476] [r740-64-137:2207514:0]         cuda_md.c:162  UCX  ERROR cuMemGetAddressRange(0x7fbe18000000) error: named symbol not found
[1657658579.823830] [r740-64-137:2207514:0]         cuda_md.c:162  UCX  ERROR cuMemGetAddressRange(0x7fbe14000000) error: named symbol not found
/root/github/SRF/src/tests/test_network.cpp:123: Failure
Expected: (h_ucx_block.remote_handle_size()) <= (d_ucx_block.remote_handle_size()), actual: 22 vs 13
[  FAILED  ] TestNetwork.ResourceManager (1022 ms)
```

**Steps/Code to reproduce bug**
Run the cpp tests as described in CONTRIBUTING

**Expected behavior**
Test passes

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of SRF install: [conda]

**Environment details**
Please run and paste the output of the `./scripts/print_env.sh` script here, to gather any other relevant environment details

**Additional context**
lstopo of host machine
https://gist.github.com/pdmack/08dbbc3ce195d3fd76b01524e871f17e 

lscpu snippet
```
CPU(s):                          80
On-line CPU(s) list:             0-79
Thread(s) per core:              2
Core(s) per socket:              20
Socket(s):                       2
NUMA node(s):                    2
```

**Comment by ryanolson** [comment]
This has been fixed in this commit: https://github.com/ryanolson/srf/commit/cc1c5350ad3c7a98a9d29194e26f633f7bf3c947
