### ISSUE TITLE
Delete Unused Files from Repo

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/SRF#48]
The following files are not included in any CMakeLists.txt and need to either be added or removed:

- [ ] `src/internal/control_plane/client.cpp`
- [ ] `src/internal/control_plane/server_resources.cpp`
- [ ] `src/internal/control_plane/server.cpp`
- [ ] `src/internal/data_plane/client_worker.cpp`
- [ ] `src/internal/data_plane/client.cpp`
- [ ] `src/internal/data_plane/instance.cpp`
- [ ] `src/internal/data_plane/server.cpp`
- [x] `src/public/memory/buffer_utils.cpp`
- [x] `src/public/segment/runnable.cpp`
- [x] `src/tests/test_architect.cpp`
- [x] `src/tests/test_assignment_manager.cpp`
- [x] `src/tests/test_network.cpp`
- [ ] `src/tests/test_options.cpp`
- [ ] `src/tools/topology_exporter.cpp`
- [ ] `tests/test_memory.cpp`
- [x] `tests/test_remote_descriptor.cpp`
- [x] `tests/test_runnable.cpp`
- [x] `tests/test_rx.cpp`
- [ ] `tests/test_segment_components.cpp`
- [ ] `tests/test_segment.cpp`

Releated to #8

**Comment by ryanolson** [comment]
please don't delete control_plane or data_plane folder, those will be re-enable in a pull request this week or next.

**Comment by mdemoret-nv** [comment]
Ok, thats exactly why I made this issue instead of just deleting it. Can you indicate which files should be deleted, which should be kept but not included, and which should be added to the CMakeLists?

**Comment by ryanolson** [comment]
Do you want check marks on the ones that should be deleted?

**Comment by mdemoret-nv** [comment]
Sure, that works.
