### ISSUE TITLE
[FEA] Re-Enable `src/tests/test_options.cpp`

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/SRF#55]
**Is your feature request related to a problem? Please describe.**
Discovered in issue #48, some tests have been removed from the compilation and therefore they are no longer run.

The test file `src/tests/test_options.cpp` was one of these files that was disabled. It should be re-enabled and the tests updated.

**Comment by ryanolson** [comment]
Will merge these into `test_partitions.cpp`.  WIP.
