### ISSUE TITLE
[FEA] Need a way to block on segment initialization

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/SRF#68]
**Is your feature request related to a problem? Please describe.**
In Morpheus we need a way to block until the segment initializer has been called. 
https://github.com/nv-morpheus/Morpheus/issues/188

Currently Morpheus is building the pipeline with:
```
self._srf_pipeline.make_segment("main", inner_build)

self._srf_executor.register_pipeline(self._srf_pipeline)

self._is_built = True
```

The problem is that `inner_build` is called asynchronously and we need a way to wait until after `inner_build` is called.

**Describe the solution you'd like**
Probably some sort of blocking call that we can make like:
`wait_for_segment_init` 

**Additional context**
In Morpheus we don't have the full detail of the messages passed between nodes until the pipeline is fully built, which doesn't happen until the segment initialize is called.

**Comment by ryanolson** [comment]
It is not safe to assume that every segment defined in a pipeline will be instantiated.

If the primary motivation here is to generate a viz file, we should be able to do it from the pipeline definition and proto serialization; however, in the case of python, we not be able to generate full type information.
